# Generated by Django 3.2.9 on 2021-11-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211028_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_data',
            name='company_image',
            field=models.CharField(max_length=2083),
        ),
    ]
