# Generated by Django 3.2.9 on 2021-11-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_company_data_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_data',
            name='company_image',
            field=models.ImageField(default='DEFAULT VALUE', null=True, upload_to='images/'),
        ),
    ]
