# Generated by Django 3.2.9 on 2021-11-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_company_data_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_data',
            name='company_image',
            field=models.CharField(default=1, max_length=2083),
            preserve_default=False,
        ),
    ]
